name: Build Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libpcap-dev
    
    - name: Compile
      run: make

  arm-build: 
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          
    - name: Compile
      run: make
